# Generated by Django 4.0.4 on 2022-07-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='act',
        ),
    ]
