# Generated by Django 4.0.4 on 2022-07-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_news_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='show',
        ),
    ]
