# Generated by Django 4.0.4 on 2022-07-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
