# Generated by Django 4.0.4 on 2022-07-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-show']},
        ),
    ]
