# Generated by Django 4.0.4 on 2022-07-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.IntegerField(),
        ),
    ]
