# Generated by Django 4.0.4 on 2022-07-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='website',
        ),
    ]
