# Generated by Django 4.0.4 on 2022-07-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_remove_contactform_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='msg',
        ),
    ]
