# Generated by Django 4.0.4 on 2022-07-30 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_rename_message_contactform_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
