# Generated by Django 4.0.4 on 2022-07-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_contactform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
