# Generated by Django 4.0.4 on 2022-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_fb_main_link_main_tell_main_tw_main_yt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.ImageField(default='-', upload_to=''),
        ),
    ]
