# Generated by Django 4.0.4 on 2022-07-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
