# Generated by Django 4.0.4 on 2022-07-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_main_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
