# Generated by Django 4.0.4 on 2022-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default='pass@gmail.com', max_length=254),
        ),
    ]
